### ISSUE TITLE
Not able to find vulnerabilities in packages.json

### ISSUE THREAD

**Issue by sweco-nltbim** [fatihtokus/scan2html#10]
When using the Trivy plugin as a task in Azure DevOps pipelines, It is able to detect packages.json and find vulnerabilities. When using this plugin, the vulnerabilities are 0.

Trivy in Azure DevOps:

![image](https://github.com/fatihtokus/scan2html/assets/93710799/b5d52ead-913a-47c8-8731-d7bca66bc487)

Scan2html results:

![image](https://github.com/fatihtokus/scan2html/assets/93710799/cd19a8d1-e2c3-43de-85d6-f7e5e07ec394)

**Comment by fatihtokus** [comment]
Hi @sweco-nltbim,

I am glad to hear that this plugin is useful for you. Please do not hesitate to get in touch with us if you need any help! or require any improvements.

If you don't mind, could you do a favor by giving us a star :)

Regards,
Fatih
