### ISSUE TITLE
Error: Invalid cross-device link

### ISSUE THREAD

**Issue by BoyanYK** [fatihtokus/scan2html#134]
First of all, thanks for the great work! I really love the much more comprehensive report this tool generates.

Since the new release (0.3.10) I have been encountering errors when using the plugin. Here are the command and output (some details omitted for privacy reasons):
```
trivy scan2html image --exit-code 0 --cache-dir .trivycache $DOCKER_IMAGE --scan2html-flags --output trivy_vuln_report.html
INFO	Scan2html started
INFO	RetrievePluginFlagsAndCommand: [/root/.trivy/plugins/scan2html/scan2html image --exit-code 0 --cache-dir .trivycache IMAGE:TAG --scan2html-flags --output trivy_vuln_report.html]
INFO	RetrievePluginFlagsAndCommand - pluginFlags: map[--output:trivy_vuln_report.html --report-title:Trivy Report --scan2html-flags:]
INFO	RetrievePluginFlagsAndCommand - trivyFlags: [/root/.trivy/plugins/scan2html/scan2html image --exit-code 0 --cache-dir .trivycache  IMAGE:TAG  --format json --output /tmp/scan2html-temp-report.json]
INFO	Run the Trivy command: trivy image --exit-code 0 --cache-dir .trivycache  IMAGE:TAG  --format json --output /tmp/scan2html-temp-report.json
INFO	Generated Json report: /tmp/scan2html-temp-report.json with size of: 353060 bytes
INFO	GenerateHtmlReport: map[--output:trivy_vuln_report.html --report-title:Trivy Report --scan2html-flags:]
INFO	Base Directory: /root/.trivy/plugins/scan2html
INFO	With EPSS: false
INFO	Report Title: Trivy Report
INFO	Report Name: trivy_vuln_report.html
FATAL	Error generating HTML report: failed to replace report title in trivy_vuln_report.html: rename /tmp/modified_3212693046 trivy_vuln_report.html: invalid cross-device link
```
The error is of course the last line:
`FATAL	Error generating HTML report: failed to replace report title in trivy_vuln_report.html: rename /tmp/modified_3212693046 trivy_vuln_report.html: invalid cross-device link`

This error happens both in a Gitlab CI job and when running locally (ZSH on Linux).

Looking at the `tmp` folder, I can see the file `/tmp/modified_3212693046` and it is the correct HTML report. No file with the name `/tmp/modified_3212693046 trivy_vuln_report.html` exists.
Seems like the issue is that using the space as part of the filename when creating the temp file

**Comment by fatihtokus** [comment]
Hi @BoyanYK ,

Thanks for opening the issue. We have fixed it via v0.3.13, please retry and let us know.

Regards,
Fatih
