### ISSUE TITLE
Respect --output flag passed to trivy command

### ISSUE THREAD

**Issue by BoyanYK** [fatihtokus/scan2html#140]
Currently, when running a command with `trivy scan2html`, not all flags passed to trivy itself are correctly respected.

More specifically, in a command such as `trivy scan2html --format json --output trivy.json nginx` we don't get a file called `trivy.json` - which I need for further reports to be generated.

While I can get it out of the `/tmp/` folder where scan2html itself redirects the json result, this is risky as already due to a recent update of the plugin the path to the json changed, so it doesn't seem like a good idea to rely on a path that the plugin uses internally.

I would suggest to scan for those arguments provided by the user, and ideally copy the plugin generated json output also to the location specified by the user.

**Comment by fatihtokus** [comment]
Hi @BoyanYK ,

Thanks for opening the issue. The main purpose of this plugin is to generate an interactive HTML report on top of the JSON output. Therefore, the '--output flag' is reserved for scan2html. 

But if you want to get JSON output you don't need to use this plugin, trivy can directly generate it for you (trivy --format json --output trivy.json nginx ...)

I am unsure that generating two outputs (HTML and JSON) at the same will make sense, and will not confuse the users.

I see you are a good user of scan2html. So I would like to get your opinion on another feature though. We are planning to add deduplication of vulnerabilities as well. Say report will show a distinct list of the vulnerabilities but an option to see duplicated ones as well.

What do you think?

Regards,
Fatih

**Comment by fatihtokus** [comment]
[test.md](https://github.com/user-attachments/files/18166168/test.md)

**Comment by fatihtokus** [comment]
We are developing something like this, adding a new checkbox 'Enable Deduplication': 

![image](https://github.com/user-attachments/assets/ed53de7b-4173-4b3a-b1ba-d4d38c94dfae)
