### ISSUE TITLE
There is some error when I run "trivy scan2html image"

### ISSUE THREAD

**Issue by cww1769** [fatihtokus/scan2html#5]
oot@ubuntu-server:/home/chenwei# trivy scan2html image proxy:v2.4.0 result.html
/root/snap/trivy/215/.trivy/plugins/scan2html/scan2html: line 24: trivy: command not found
Error: plugin error: plugin exec: exit status 127
Usage:
  trivy scan2html [flags]

Flags:
  -h, --help   help for scan2html

Global Flags:
      --cache-dir string          cache directory (default "/root/snap/trivy/215/.cache/trivy")
  -c, --config string             config path (default "trivy.yaml")
  -d, --debug                     debug mode
      --generate-default-config   write the default config to trivy-default.yaml
      --insecure                  allow insecure server connections
  -q, --quiet                     suppress progress bar and log output
      --timeout duration          timeout (default 5m0s)
  -v, --version                   show version

2023-07-15T23:51:22.381+0800	FATAL	plugin error: plugin exec: exit status 127

**Comment by fatihtokus** [comment]
Hi @cww1769 ,

I have fixed the issue in the latest version v0.2.1. Could you please retry it with the latest version?

1. Install/update $ trivy plugin install github.com/fatihtokus/scan2html
2. $ trivy scan2html image proxy:v2.4.0 result.html

Many thanks.
