### ISSUE TITLE
Feature Request: Reading multiple reports at the same time

### ISSUE THREAD

**Issue by prasenjitsh** [fatihtokus/scan2html#56]
Hi Team,

I'm running Trivy commands twice in pipeline: is there any way to combine the output html and show single file? or I need to display in 2x different html?  additionally, if it's not possible to display the combine html - is it possible to configure the left side menu to show exactly what we want to show?

1. first run to capture the vulnerabilities on my code and dependent packages
2. find secrets in my code

`trivy scan2html rootfs --exit-code 1 . --skip-files "*.deb" --ignore-unfixed --scanners vuln --severity CRITICAL,HIGH,MEDIUM output.html`

`trivy scan2html rootfs --exit-code 0 . --skip-files "*.deb" --skip-dirs "venv" --scanners secrets --severity CRITICAL,HIGH,MEDIUM` output1.html

**Comment by prasenjitsh** [comment]
HI @fatihtokus ,

1. We are running Trivy as part of our Azure DevOps pipeline. Please see the screenshot below. These reports will be available in the release pipeline for six months for auditing purposes.
2. I was actually looking to see if we can hide those menus that are not required. If you see the screenshot, currently, I’m scanning one time for vulnerabilities and another time for secrets. I am planning to implement SBOM and K8 scanner in the future. Each of the tabs should have only one report visible instead of the entire menu list, so that developers don’t get confused.

<img width="1152" alt="Screenshot 2024-06-07 at 10 20 30 AM" src="https://github.com/fatihtokus/scan2html/assets/40861523/7ee0ee2e-e63e-4c34-8fae-ceaa1f75be72">

**Comment by fatihtokus** [comment]
Hi @prasenjitsh ,

Thanks for the answers:
1.   We are planning to accept multiple trivy-results.json reports as url parameters like below.
scan2html-empty-report.html?url=https://$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/$CI_JOB_ID/artifacts/trivy-vuln-results.json&https://$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/$CI_JOB_ID/artifacts/trivy-secrets-results.json
Would this address your requirement?

2- As a quick solution I will collapse the menu and open the filled one as default, will this help you?

**Comment by prasenjitsh** [comment]
Hi @fatihtokus ,

1. Can it load from local directory instead of https? Since I will be running from from pipeline it will be easy to load from local machine.
2. yes that will help

**Comment by fatihtokus** [comment]
1- unfortunately, due to the browsers' security limitations, it has to come via https :( Do you think it still will be useful for you?
2- We have started working on this.

**Comment by prasenjitsh** [comment]
1. I have to see. I can publish the JSON as azure pipeline artifacts. I have to verify whether these artifacts can be accessed via https from shell.

**Comment by fatihtokus** [comment]
Hi @prasenjitsh ,
1- Still working on this, will update you soon
2- We have released this, please try and give us feedback.

Regard

**Comment by fatihtokus** [comment]
Hi @prasenjitsh ,

1- We have delivered this as well, please give it a try and let us know your feedback
2- Any feedback?

**Comment by prasenjitsh** [comment]
Hi,

Point# 2 is working. I will check in point #1 and let you know.
