### ISSUE TITLE
html report not readable

### ISSUE THREAD

**Issue by Lahcentidrarin** [fatihtokus/scan2html#65]
i run a trivy scan on my cluster k8s with the plugin scan2html, i got a report not readable on browsers 
i tested it on https://codepen.io/ and i got a javascript error  "Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')"

trivy version: 0.52.2
scan2html version : latest 

any solution please

**Comment by fatihtokus** [comment]
Hi @Lahcentidrarin ,

Thank you for using our plugin. Could you give us more details?

1.  What command did you execute?
2. What is the size of the report?
3. Could you upload a screenshot?

Regards,
Fatih

**Comment by Lahcentidrarin** [comment]
Hi @fatihtokus 

Thank you for your response


Here is the command: trivy scan2html k8s --report all --include-namespaces xxx interactive_result.html
the size is 1.1M
actualy i got a white page on browser and when i refresh i see kind some of the content but it disappear quickly.

**Comment by fatihtokus** [comment]
Hi @Lahcentidrarin ,

1- Can you try following and let me know if still it works? trivy scan2html k8s --report all  interactive_result.html
2- Can you share the interactive_result.html file ?
3- Can you share the console(like below) that shows the error stack trace so that we can debug?
![image](https://github.com/fatihtokus/scan2html/assets/19647150/6fe3823f-44c4-46fd-96ef-baac9e6a331b)

**Comment by Lahcentidrarin** [comment]
Hi @fatihtokus 
Unfortunatly i can't share the report 
here is sceen of the console
![Capture d’écran 2024-07-01 122241](https://github.com/fatihtokus/scan2html/assets/125581494/5abf422b-0526-4ced-a4f2-c84af6686766)

**Comment by fatihtokus** [comment]
Hi @Lahcentidrarin,

Unfortunately, without the report, we couldn't reproduce it locally. But we put some extra checks with the latest release. Please try and let us know.

please consider giving us a GitHub star ⭐️. Thank you!

**Comment by fatihtokus** [comment]
Hi @Lahcentidrarin,

By any chance, have you tried the latest version?

**Comment by fatihtokus** [comment]
Hi @Lahcentidrarin ,

Have you tried the latest version which has excellent features like creating report from multiple json scan results?
