### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by Deathstr0ke1** [fatihtokus/scan2html#66]
Hi Team,

Is there a plan to develop a simple management page? I have scan result reports for multiple K8s clusters, and I would like to quickly navigate to the scan results of different clusters within the management page (both HTML and JSON loading are acceptable).

**Comment by fatihtokus** [comment]
Hi @Deathstr0ke1 ,

Thanks for using the plugin. Did you know that we already have the feature? 
- Open any report that you already generated by using the plugin.
- Open the 'Load a Report' menu
- Select a JSON report
![image](https://github.com/fatihtokus/scan2html/assets/19647150/fb741d08-54f0-4380-9604-7fcdd599a4d3)

**Comment by Deathstr0ke1** [comment]
Thank you for your response.
I understand the feature you mentioned. Perhaps what I need is the ability to load multiple reports simultaneously. For example, if there are multiple JSON-format reports in a folder, I would like to be able to click on the webpage to switch between different reports, similar to your  #issue58.

**Comment by fatihtokus** [comment]
Actually, that functionality is also available:
1. Make your JSON reports available via a url (https://fatih.tokus.gitlab.io/-/scan2html-test/-/jobs/7034668797/artifacts/results.json)
2. Open any report that you already generated by using the plugin and pass the JSON report url as a parameter (interactive_report.html?reportUrls=https://fatih.tokus.gitlab.io/-/scan2html-test/-/jobs/7034668797/artifacts/results.json)
3. if you want to load multiple reports at the same time -> interactive_report.html?reportUrls=https://fatih.tokus.gitlab.io/-/scan2html-test/-/jobs/7034668797/artifacts/results.jsonreportUrls=https://fatih.tokus.gitlab.io/-/scan2html-test/-/jobs/7034668797/artifacts/results2.json

**Comment by Deathstr0ke1** [comment]
Oh, I see.
Thank you for your response, again.

**Comment by fatihtokus** [comment]
@Deathstr0ke1, good news for you. this feature is released. Please try and let me know what you think.

The usage: trivy scan2html generate single_unified_report.html from sbom.json k8s.json ...
