### ISSUE TITLE
I cannot install the plugin - 404 Not Found

### ISSUE THREAD

**Issue by sweco-nltbim** [fatihtokus/scan2html#83]
As of today I was unable to install the plugin with the command **trivy plugin install github.com/fatihtokus/scan2html**. I get a 404 not found as a response.

![image](https://github.com/user-attachments/assets/9e926e7c-9874-41dc-90a6-354e24f09678)

I use the latest Trivy version (v0.54.0)

**Comment by fatihtokus** [comment]
Hi @sweco-nltbim ,

We have tested in our lab, it is a defect in trivy which we reported here: https://github.com/aquasecurity/trivy/discussions/7272

Regards

**Comment by sweco-nltbim** [comment]
> Hi @sweco-nltbim ,
> 
> We have tested in our lab, it is a defect in trivy which we reported here: [aquasecurity/trivy#7272](https://github.com/aquasecurity/trivy/discussions/7272) please use the previous version of trivy for the timebeing
> 
> Regards

Ok, thanks for the update.

**Comment by fatihtokus** [comment]
Hi @sweco-nltbim ,

I can see it is resolved with the latest version of trivy v0.54.1.

Regards,
Fatih
