### ISSUE TITLE
Additional columns in report 

### ISSUE THREAD

**Issue by stealthrabbi** [fatihtokus/scan2html#89]
Could this report include the last update date, reported date and the detailed description of the vuln? I know these are included in the JSON output of trivy

**Comment by fatihtokus** [comment]
Hi @stealthrabbi ,

Thanks for the feature request which we will put in the backlog. Could I know if you are using the plugin actively for any project?

Regards,
Fatih

**Comment by stealthrabbi** [comment]
@fatihtokus no, I haven't used this plugin yet! I like the look of the report and am looking for something a bit nicer than the CSV output I have using a custom template

**Comment by stealthrabbi** [comment]
I am now using this plugin now that trivy has a built in way to install plugins.

**Comment by fatihtokus** [comment]
Hi @stealthrabbi , 

We have finished the implementation and will release it this weekend.
Did you know that you can include EPSS scores as well?
 -> trivy scan2html image alpine:latest --scan2html-flags --output interactive_report.html --with-epss --report-title "Trivy Report Title - 07-11-2024 etc"

**Comment by stealthrabbi** [comment]
Looks good, thanks @fatihtokus . TO be clear, this feature is adding the EPSS scores, not the report/update dates or detailed description?

**Comment by fatihtokus** [comment]
Yes, I just shared a new feature of EPSS that we recently released. Your request will be released this weekend

**Comment by fatihtokus** [comment]
We have released the report/update dates or detailed description, please try @stealthrabbi
