### ISSUE TITLE
Support for Generating a Single Interactive Report and Loading multiple Trivy JSON Reports in scan2html

### ISSUE THREAD

**Issue by rajeev-cs** [fatihtokus/scan2html#91]
Hi Team,

I am currently using the scan2html plugin in my GitLab CI/CD pipeline.

The script iterates over the scan targets (config, image, fs) and formats (json, cyclonedx, spdx, template), running Trivy scans and generating reports.
Generates SBOM reports with trivy sbom and uses the scan2html plugin to create HTML reports.
Artifacts are saved for review.

to generate SBOM reports in HTML format. The plugin works well, but I have a few feature requests that would greatly enhance its functionality.

1) Single Interactive Report:

It would be beneficial to have an option to generate a single interactive report that consolidates all scans (vulnerabilities, misconfigurations, licenses) into one view, making it easier to navigate and review the results.

2) Loading multiple Trivy JSON Reports:

Currently, I can see there is an option to load only 1 JSON file. The SBOM HTML report generated by scan2html could be improved by adding an option to load a multiple Trivy JSON reports. This feature would allow users to display all vulnerabilities, misconfigurations, and licenses within the interactive HTML report.
These features would streamline the reporting process and make it easier for teams to analyze scan results comprehensively.

Thank you for considering these enhancements!

**Comment by rajeev-cs** [comment]
@fatihtokus Thanks for this feature this is very helpful for us.

**Comment by fatihtokus** [comment]
Please keep sharing your feature reguests
