### ISSUE TITLE
Commands to generate a single report from multiple trivy json scan reports

### ISSUE THREAD

**Issue by stealthrabbi** [fatihtokus/scan2html#95]
Is there a single command we can use with this plugin to generate a report that has all the vulnerabilities and the SBOM report, filesystem findings, etc? I am guessing not since this requires separate trivy commands.

**Comment by stealthrabbi** [comment]
Or maybe there's a way to specify multiple .json files outputted from a trivy scan, and then combine those in to the HTML report?

**Comment by fatihtokus** [comment]
Hi @stealthrabbi ,

Thanks for the tkt, could you put your thoughts here(https://github.com/fatihtokus/scan2html/discussions/92#discussioncomment-10512591), please?
